### PR TITLE
USMilCoin UMC

### PR DESCRIPTION
**Pull request by cadetkelley**

### CODE REVIEW

**Comment by cadetkelley** [comment]
0xb81bbb68d2c32398e628f5183d1cfe9f24dfb678

**Comment by cadetkelley** [comment]
USMilCoin UMC
0xb81bbb68d2c32398e628f5183d1cfe9f24dfb678

**Comment by cadetkelley** [comment]
Good day,
I have tried following the process to upload a logo to my token.
I think i have it all mixed up

**Comment by kolya182** [comment]
Can i ask you where exactly did you read that this repo is correct place to upload the log ?.

**Pull request closed without merging**
