### PR TITLE
XCOIN (XCN)

### PR DESCRIPTION
**Pull request by ipsum24**
### XCOIN (XCN) is the digital coin for online transactions and purchases. Users can  view, pay and manage your utility accounts including telecom, prepaid electricity, water, gas with XCOIN (XCN) wallet connected to the blockchain. It can also be used for purchases where XCOIN (XCN) is accepted.###

### CODE REVIEW

**Comment by cadetkelley** [comment]
XCN symbol is good. However, i just search and found that XXXcoin had got same symbol as yours.

**Comment by ipsum24** [comment]
> XCN symbol is good. However, i just search and found that XXXcoin had got same symbol as yours.

Hi, that symbol is XXXCoin (XCX), if I am not mistaken

**Comment by cadetkelley** [comment]
Just checked it again, It is XCN for XXXcoin. You can try searching for it on Trust Wallet

**Comment by terorie** [comment]
The only `XCN` token I can see on CoinMarketCap is Cryptonite.
Also, please upload token images to TrustWallet/tokens not this repo.

**Pull request closed without merging**
