### PR TITLE
add links requirement

### PR DESCRIPTION
**Pull request by Cryptocool1**

### CODE REVIEW

**Comment by Cryptocool1** [comment]
@vikmeup

**Comment by catenocrypt** [comment]
Links was added to a details page
https://github.com/trustwallet/developer/blob/master/assets/repository_details.md#infojson-contents
but apparently that page was completely removed when the assets section was simplified.

image

**Review by catenocrypt — APPROVED** [review]

**Comment by vikmeup** [comment]
https://github.com/trustwallet/developer/pull/197/files?short_path=34a62dd#diff-34a62dd5267c336b61afc528c40ca31f6562534952dcdfc568856fc4e21935e3 Still does not look good

**Comment by Pponwili1998** [comment]
Cryptocool1:patch-2

**Pull request closed without merging**
